//'use client'

import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link.js";
//import { SessionProvider } from "next-auth/react"  // client componet
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth].js";
import LoginBtn from "./LoginBtn.js"
import "./globals.css";
import LogOutBtn from "./LogOutBtn.js";
import Providers from "./Provider.js";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 let session = await getServerSession(authOptions);
 console.log(children);
 console.log(session);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar">
          <Link href={"/"} className="logo">AppleForum</Link>
          <Link href={"/list"}>List</Link>
        </div>
        <div>
          {session ? 
          <span>{session.user.name}<LogOutBtn/></span>: 
          <LoginBtn></LoginBtn>
        }
        </div>
        <Providers>
          {children}
        </Providers>
        {/* <SessionProvider>
          {children}
        </SessionProvider> */}
      </body>
    </html>
  );
}
